Feat/communications
effectussoftware/pis-effectus-api pull request #10
Opened 2020-09-26 20:05 UTC by kaozdl

#### Trello ticket:
Como usuario debo poder ver un feed de Novedades al entrar a la app (8)

------
#### How I solved it:
agrego communication model con title, text, published TODO: image

------
#### Refactors or changes not directly related to the main purpose of this PR:

------
#### API expected request/response:
Api list
```
[
  {
     id: 1,
     title: 'some title',
     text: 'some text',
     published: false,
     created_at: ...,
     updated_at: ...
  }
]
```

Api show
```
  {
     id: 1,
     title: 'some title',
     text: 'some text',
     published: false,
     created_at: ...,
     updated_at: ...
  }
```

2020-10-03 17:51 UTC, DJA89 commented on .rubocop.yml
> +AllCops:
Esto me intriga nomás, por qué aparece como nuevo 🤔

2020-10-03 17:53 UTC, DJA89 commented on Gemfile
> +  gem 'byebug', platforms: %i[mri mingw x64_mingw]
ídem, esto ya está así en master, por qué lo marca como nuevo

2020-10-03 17:55 UTC, DJA89 commented
Estás 12 commits behind master, por favor rebasea

2020-10-04 18:36 UTC, DJA89 commented
Bueno vuelvo a preguntar, por qué muestra como nuevas pilas de cosas que ya están?

2020-10-10 17:19 UTC, facundotorterola requested changes

2020-10-10 17:19 UTC, facundotorterola commented on app/controllers/api/v1/admin/communication_controller.rb
> +class Api::V1::Admin::CommunicationController < ApplicationController
Los controllers dentro del admin tienen que heredad de  Api::V1::Admin::AdminApiController

2020-10-10 17:19 UTC, facundotorterola commented on app/controllers/api/v1/admin/communication_controller.rb
> +    render json: @communications, status: :ok
con Jbuilder no es necesario renderizar el json

2020-10-10 18:41 UTC, facundotorterola commented on app/models/communication.rb
> +  end
los valores por default los estamos poniendo en el schema

2020-10-10 18:51 UTC, facundotorterola approved these changes

2020-10-10 19:08 UTC, guzmanmo approved these changes

2020-10-10 19:25 UTC, merged

2020-10-11 15:23 UTC, DJA89 commented on app/models/communication.rb
> +  end
Post mortem but, what is this for?

2020-10-11 15:25 UTC, DJA89 commented on spec/factories/communications.rb
> +  end
Use Faker for this

2020-10-11 15:34 UTC, DJA89 commented on spec/models/communication_spec.rb
> +end
Add actual tests