create app.json for review apps
effectussoftware/pis-effectus-api pull request #23
Opened 2020-10-04 00:59 UTC by guzmanmo

#### Trello ticket:

------
#### How I solved it:
Manifiesto necesario para review apps en heroku

------
#### Refactors or changes not directly related to the main purpose of this PR:

------
#### Screenshots:

------
#### API expected request/response:

2020-10-04 16:15 UTC, kaozdl approved these changes

2020-10-04 18:33 UTC, DJA89 requested changes

2020-10-04 18:33 UTC, DJA89 commented on app.json
> +      "postdeploy": "bundle exec rails db:seed"
Falla el deploy, dice `Run `rails db:migrate` to update your database then try again.`

2020-10-05 20:40 UTC, DJA89 approved these changes

2020-10-05 20:40 UTC, merged