add authentication to api controller
effectussoftware/pis-effectus-api pull request #29
Opened 2020-10-12 14:38 UTC by facundotorterola

#### Trello ticket:

------
#### How I solved it:

agregue la authenticacion al api controller que hereda de los demas
------
#### Refactors or changes not directly related to the main purpose of this PR:

------
#### Screenshots:

------
#### API expected request/response:

2020-10-12 16:42 UTC, DJA89 commented on app/controllers/api/v1/admin/authentication_admin_controller.rb
> +        skip_before_action :authenticate_api_v1_user!
Seeing as the Admin has its own authentication, we could probably skip this for all the Admin controllers directly, what do you think?

2020-10-12 16:43 UTC, DJA89 requested changes

2020-10-12 16:43 UTC, DJA89 commented on app/controllers/api/v1/authentication_controller.rb
> +      skip_before_action :authenticate_api_v1_user!
Leave a space after the skip

2020-10-15 20:25 UTC, DJA89 approved these changes

2020-10-15 20:41 UTC, guzmanmo approved these changes

2020-10-15 20:42 UTC, merged