add tests for communications
effectussoftware/pis-effectus-api pull request #30
Opened 2020-10-14 03:06 UTC by kaozdl

#### Trello ticket:

crud de communications
agrego tests y un par de issues con jbuilder
------
#### How I solved it:

------
#### Refactors or changes not directly related to the main purpose of this PR:

------
#### Screenshots:

------
#### API expected request/response:

2020-10-14 13:20 UTC, facundotorterola requested changes

2020-10-14 13:20 UTC, facundotorterola commented on spec/requests/communications/update_spec.rb
> +        expect(bd_communication.text).to eq 'Lala'
la response de un update tiene que ser el recurso actualizado

2020-10-14 13:20 UTC, facundotorterola commented on spec/requests/communications/create_spec.rb
> +        expect(created_communication.published).to eq true
Cuando creas un recurso hay que listarlo como comunication{
  'title': ....
...
}

2020-10-14 13:20 UTC, facundotorterola commented on spec/requests/communications/create_spec.rb
> +        expect(response).to have_http_status 204
El text es requerido y no el title ? deberia lanzar un error no 204

2020-10-14 13:20 UTC, facundotorterola commented on spec/requests/communications/destroy_spec.rb
> +        expect(response).to have_http_status 204
Debería mostrar el recurso que borraste

2020-10-14 13:20 UTC, facundotorterola commented on spec/requests/communications/destroy_spec.rb
> +
Estaria bueno un test si queres borrar algo que no esta en la base de datos

2020-10-14 19:52 UTC, kaozdl commented on spec/requests/communications/create_spec.rb
> +        expect(response).to have_http_status 204
el title es requerido y el text no, por eso devuelve 204, efectivamente crea la communication

2020-10-14 19:52 UTC, kaozdl commented on spec/requests/communications/destroy_spec.rb
> +        expect(response).to have_http_status 204
tenemos esto especificado en algún lado?

2020-10-15 22:10 UTC, facundotorterola approved these changes

2020-10-15 22:11 UTC, facundotorterola approved these changes

2020-10-15 22:12 UTC, guzmanmo submitted a review, later dismissed

2020-10-15 22:20 UTC, facundotorterola approved these changes

2020-10-15 22:20 UTC, guzmanmo approved these changes

2020-10-15 22:22 UTC, merged