feat: push notification for communications
effectussoftware/pis-effectus-api pull request #34
Opened 2020-10-18 00:39 UTC by DJA89

#### Trello ticket:

https://trello.com/c/sIHymdos/17-como-usuario-debo-poder-ser-notificado-cuando-se-publica-un-nuevo-comunicado-3

------
#### How I solved it:

Added after_update to Communication

------
#### Refactors or changes not directly related to the main purpose of this PR:

* Created scope for active users
* Forbid updates for a published communication
------
#### Screenshots:

------
#### API expected request/response:

2020-10-20 19:34 UTC, guzmanmo commented on spec/requests/communications_spec.rb
> +RSpec.describe 'Communications', type: :request do
porque todos los test en un unico archivo y no separados por "Post", "Update", etc..

2020-10-20 20:57 UTC, DJA89 commented on spec/requests/communications_spec.rb
> +RSpec.describe 'Communications', type: :request do
Se usa un sólo archivo de pruebas por archivo que se testea, en este caso este archivo se relaciona con el communications_controller.

2020-10-21 22:08 UTC, facundotorterola requested changes

2020-10-21 22:08 UTC, facundotorterola commented on spec/requests/communications_spec.rb
> +RSpec.describe 'Communications', type: :request do
con kalil habiamos quedado de hacer un archivo de test por cada funcion create,update etc

2020-10-21 22:08 UTC, facundotorterola commented on app/models/communication.rb
> +  end
Estamos arreglando lo mismo

2020-10-22 00:54 UTC, DJA89 commented on spec/requests/communications_spec.rb
> +RSpec.describe 'Communications', type: :request do
Les digo, en lo normal de Ruby on Rails/RSpec, antes se solían hacer tests de controladores específicamente, esos tests tenían un archivo por controlador como es de esperar, Rails es Convention over Configuration para que todo sea fácil de encontrar.

Al empezar a hacer estos request specs yo en principio los traté como lo mismo, porque al menos hasta ahora venimos haciendo exactamente lo mismo que un controller_spec, sólo que pasando por el router de Rails, por lo cual mi inclinación es a usar la misma estructura. A partir de sus comentarios estuve leyendo al respecto y por lo que veo los requests spec se usan también para probar más de un endpoint en un mismo spec, por ejemplo podés probar que al hacer un create por un Admin de un evento un Usuario pueda ver ese evento cuando hace un GET de eventos,.

Este tipo de ejemplo y otros más complicados hacen que no sea tan claro para mi dónde meter los Request specs, por lo cual lo que hice fue poner una pregunta en StackOverflow sobre cuál sería la estructura correcta para los request specs. De momento lo vuelvo para atrás como ustedes quieren (Si bien opino que no es lo más correcto) y ta, si contestan vemos qué hacemos.

2020-10-22 01:50 UTC, DJA89 commented on spec/requests/communications_spec.rb
> +RSpec.describe 'Communications', type: :request do
Ahí subí el cambio

2020-10-23 00:30 UTC, facundotorterola requested changes

2020-10-23 00:30 UTC, facundotorterola commented on app/models/communication.rb
> +  validate :cant_update_if_published
falta validacion de si es recurrente no se puede editar

2020-10-24 17:11 UTC, guzmanmo approved these changes

2020-10-24 17:15 UTC, facundotorterola approved these changes

2020-10-24 17:15 UTC, merged