Se creo la feature crear surveys para preguntas de tipo numeric y range
effectussoftware/pis-effectus-api pull request #91
Opened 2021-12-17 18:08 UTC by CristianOehler

#### Trello ticket:

------
#### How I solved it:

------
#### Refactors or changes not directly related to the main purpose of this PR:

------
#### Screenshots:

------
#### API expected request/response:

2021-12-17 18:19 UTC, amonetti commented on app/controllers/api/v1/admin/answers_controller.rb
> +            # @answers = sort_answers if params[:sort]
Sacar la línea comentada

2021-12-17 18:19 UTC, amonetti commented on app/controllers/api/v1/admin/answers_controller.rb
> +module Api
Hay muchas lineas en el archivo mal indentadas

2021-12-17 18:19 UTC, amonetti commented on app/controllers/api/v1/admin/answers_controller.rb
> +            @answer = Answer.find(params[:id])
Esto se puede mover a un before_action dado que se repite en varios lados

2021-12-17 18:19 UTC, amonetti commented on app/controllers/api/v1/admin/answers_controller.rb
> +            sort = Oj.load(params[:sort])
Qué hace `Oj.load`?

2021-12-17 18:19 UTC, amonetti commented on app/controllers/api/v1/admin/authentication_admin_controller.rb
> +          @user = User.find_by id:1
No debería estar hardcoded el user_id 1

2021-12-17 18:19 UTC, amonetti commented on app/controllers/api/v1/admin/questions_controller.rb
> +                @question = Question.find(params[:id])
Mover a un before_action

2021-12-17 18:19 UTC, amonetti commented on app/controllers/api/v1/admin/questions_controller.rb
> +                  if @questions == nil
Siempre sería nil, no? Porque no está definida antes

2021-12-17 18:19 UTC, amonetti commented on app/models/answer.rb
> +
Hay una línea en blanco de más

2021-12-17 18:19 UTC, amonetti commented on app/models/answer.rb
> +            return if Integer(value) rescue nil != nil
Para qué se hace `rescue nil != nil`

2021-12-17 18:22 UTC, joacofreyer requested changes

2021-12-17 18:22 UTC, joacofreyer commented on app/controllers/api/v1/admin/answers_controller.rb
> +                @answers = questions.answers
que pasa si no encuentra question?

2021-12-17 18:22 UTC, joacofreyer commented on app/controllers/api/v1/admin/answers_controller.rb
> +                @answers = user.answers
idem arriba

2021-12-17 18:22 UTC, joacofreyer commented on app/controllers/api/v1/admin/answers_controller.rb
> +                                                )
idem, si question no se encuentra, falla la creación.
Cuando usas find_by tenes que verificar la existencia de ese objeto.

2021-12-17 18:22 UTC, joacofreyer commented on app/controllers/api/v1/admin/answers_controller.rb
> +            @answer.update!(answer_params)
indentation

2021-12-17 18:22 UTC, joacofreyer commented on app/controllers/api/v1/admin/authentication_admin_controller.rb
>            new_auth_header = @user.create_new_auth_token
por que esto? no se usa mas?

2021-12-17 18:22 UTC, joacofreyer commented on app/controllers/api/v1/admin/questions_controller.rb
> +                @question.update!(question_params)
same

2021-12-17 18:22 UTC, joacofreyer commented on app/controllers/api/v1/admin/questions_controller.rb
> +                survey = get_survey(params[:question][:survey_id])
mismo que arriba, find_By

2021-12-17 18:22 UTC, joacofreyer commented on app/controllers/api/v1/admin/questions_controller.rb
> +        end
lineas vacias no van

2021-12-21 16:04 UTC, joacofreyer requested changes

2021-12-21 16:04 UTC, joacofreyer commented on app/controllers/api/v1/admin/questions_controller.rb
> +        def create_question
renombrar a algo mas explicativo

2021-12-21 16:04 UTC, joacofreyer commented on app/controllers/api/v1/admin/questions_controller.rb
> +        def create_question
no se esta creando nada aca

2021-12-21 16:04 UTC, joacofreyer commented on app/controllers/api/v1/admin/surveys_controller.rb
> +        def set_survey
cambiar set por get

2021-12-21 16:04 UTC, joacofreyer commented on app/controllers/api/v1/admin/questions_controller.rb
> +          @question = Question.create(type: @question_type, survey_id: @survey.id,
```suggestion
          @question = Question.create!(type: @question_type, survey_id: @survey.id,
```

2021-12-21 16:04 UTC, joacofreyer commented on app/controllers/api/v1/admin/questions_controller.rb
> +          @question = Question.create(type: @question_type, survey_id: @survey.id,
buscate para que sirve poner el "!", muy util

2021-12-21 16:04 UTC, joacofreyer commented on app/controllers/api/v1/authentication_controller.rb
> +        # @user = User.find_by id:1
remove comment

2021-12-21 16:26 UTC, joacofreyer submitted a review, later dismissed

2021-12-21 17:34 UTC, vicenteferreyra reviewed
Buen PR, deje algunos comentarios pero son formas de hacer las cosas que tenemos, no es que este mal.

Faltaria agregar algunos tests de la funcionalidad que hiciste, para mantener el porcentaje de coverage que teniamos y para que le vayas agarrando la mano

2021-12-21 17:34 UTC, vicenteferreyra commented on app/controllers/api/v1/admin/answers_controller.rb
> +        end
por que tenemos un `transaction` con una sola linea? es lo mismo que poner el update suelto

2021-12-21 17:34 UTC, vicenteferreyra commented on app/controllers/api/v1/admin/answers_controller.rb
> +          end
pondria la linea 34 en el else del if, asi se hace una cosa o la otra

2021-12-21 17:34 UTC, vicenteferreyra commented on app/controllers/api/v1/admin/answers_controller.rb
> +          @answers = user.answers
lo mismo aca, si vamos a sobreescribir la variable `@answers`, dejandonos de importar lo que habia antes, lo haria en ifs

2021-12-21 17:34 UTC, vicenteferreyra commented on app/controllers/api/v1/admin/answers_controller.rb
> +        end
no es una buena practica usar metodos con prefijos `get_` o `set_`. lo que se hace en este caso es definir un metodo que se llame `answer` de la siguiente forma:

```ruby
def answer
    @answer ||= Answer.find(params[:id])
end
```

https://jtway.co/how-to-name-variables-and-methods-in-ruby-b4a21fb66c4d en este post habla un poco de eso, por si te interesa.

el operador ||= es un operador que asigna un valor solo si la parte izquierda esta en nil, de esa forma se chachea el valor y solo se hace la query a la base de datos una vez.

los otros cambios que hay que hacer en el controller son sacar los before_action y llamar al metodo `answer` en vez de la variable `@answer`

2021-12-21 17:34 UTC, vicenteferreyra commented on app/models/answer.rb
> +              end
```ruby
return if value.is_a?(Integer)
```

2021-12-21 17:34 UTC, vicenteferreyra commented on app/models/question/multi_sel.rb
> +# rubocop:disable all
por que tenemos el disable all?

2021-12-21 17:34 UTC, vicenteferreyra commented on app/models/question/multi_sel.rb
> +class Question::MultiSel < Question
le pondria MultiSelect, para no abreviar

2021-12-28 14:56 UTC, vicenteferreyra commented on app/controllers/api/v1/answers_controller.rb
> +        @answer.update!(answer_params)
aca se podria llamar al metodo `answer` en vez de la variable con @

2021-12-28 14:56 UTC, vicenteferreyra commented on app/controllers/api/v1/admin/surveys_controller.rb
> +        end
esto deberia ser igual que con @answer

2021-12-28 14:56 UTC, vicenteferreyra commented on app/controllers/api/v1/admin/surveys_controller.rb
> +          end
el transaction no es necesario, se usa para ejecutar varias operaciones en bd y hacer rollback de todo si alguna falla

2021-12-28 14:56 UTC, vicenteferreyra commented on app/controllers/api/v1/answers_controller.rb
> +      end
ponele `answers`, en rails no se usa nunca prefijos en los metodos (retrieve_algo, get_algo, set_algo no se usan)

2021-12-28 14:56 UTC, vicenteferreyra commented on app/models/question/multi_select.rb
> +# rubocop:disable all
esto no habiamos quedado de ponerlo tipo

```ruby
module Question
  class MultiSelect
```

la otra opcion es sacar esa regla de rubocop pero hacer un disable_all en un modelo no me gusta

2021-12-29 17:34 UTC, vicenteferreyra approved these changes

2021-12-29 17:44 UTC, merged